print("Getting to know you!")
myName = input("What's your name?: ")
myFood = input("What's your favourite food?: ")
myMusic = input("What's your favourite music?: ")
myLocation = input("Where do you live?: ")

print("You are")
print(myName)
print("You're probably hungry for")
print(myFood)
print("and you're definitely getting your groove on to")
print(myMusic)
print("living in the amazing")
print(myLocation)